- .github/workflows/ci.yaml
- .gitignore
- Makefile
- internal/controller/commitstatus_controller.go
To help identify slow/flaky tests. Example output here: https://app.codecov.io/gh/crenshaw-dev/promoter/tests/main
> chore(ci): report test results to codecov

- internal/controller/promotionstrategy_controller.go
- internal/controller/promotionstrategy_controller_test.go
- internal/utils/utils.go
If there are not configured active checks globally or on the previous environment do not create, a previous environment managed commit status.
Also do not create lowest level environments CommitStatus
> fix: don't create previous cs check when no actives checks configured

- docs/tool-comparison.md
Great work on this tool and thanks for putting this comparison together. I made some corrections and additions to the Codefresh section.
* Fixed product name
* Fixed error with how changes are "held"
* Added tool link to be consistent with other tools
* Added detail on how changes are tracked between applications
* Clarified "what" is promoted
* Added detail on how environments are defined
> docs: Add details on Codefresh GitOps

- internal/git/git.go
This log statement confused me a bit while debugging.
Now, it matches the rest of the error logs in the `CloneRepo` function :)
> chore(logging): Changed print statement from Info to Error

- internal/git/git.go
Prerequisite for #141
This PR aligns the environment variable for git username with `promoter_askpass.sh`.
Background:
GitLab requires a non-empty Git username to be configured, whereas GitHub does not verify when access tokens are used.
> fix: empty username in git askpass

- .gitattributes
Just makes PR diffs easier to skim.
> chore: mark generated files as generated to suppress diffs in PRs

- docs/getting-started.md
Just trying to fix the formatting in the GitHub app docs, the bullets points were not rendering properly and the webhook info was a bit hidden.
Before: 
After:
> docs: reformat GitHub app documentation

- internal/controller/pullrequest_controller.go
Very minor fix, but I was trying to figure out why it was failing to open the request but the underlying error was hidden. I'm assuming this is just an oversight, I don't see a reason not to forward the error.
> fix: wrap pull request creation error

- api/v1alpha1/constants.go
- go.mod
- go.sum
- internal/controller/promotionstrategy_controller.go
Adds an annotation called `promoter.argoproj.io/previous-environment-statuses` to the copied previous environments aggregated commit status, with a breakdown of all the active commit statuses configured and their state.
```
apiVersion: promoter.argoproj.io/v1alpha1
kind: CommitStatus
metadata:
annotations:
promoter.argoproj.io/previous-environment-statuses: |
automated-testing: pending
performance-test: pending
```
> feat: add annotation for on copied active commit status

- internal/controller/suite_test.go
Instead of going into a panic loop for tests, lets use the configured re-queue time.
The reasons tests still passed without this is because we panic and recover and so still do reconcile but that is inefficient
> fix: setup integration test to have access to settings manager

- docs/getting-started.md
- internal/scms/github/git_operations.go
`githubAppPrivateKey` is better because 1) it's more explicit, and 2) it's the same as Argo CD's key, making it easier to reuse config.
> chore!: privateKey -> githubAppPrivateKey in Secret

- internal/controller/promotionstrategy_controller.go
- internal/controller/promotionstrategy_controller_test.go
- internal/utils/utils.go
We currently rely on branch names to match environments to CTPs and to env statuses.
This PR switches to only relying on order, which significantly simplifies the code, but also means we have to be careful to enforce order and length consistency among slices.
The Reconcile loop starts by constructing a list of CTPs that exactly matches the length and order of ps.Spec.Environments.
Then it calculates the status, which starts by reconstructing the ps.Status.Environments list to match ps.Spec.Environments.
After that point, any code can use any of the three slices with confidence that they're all in sync.
> chore(refactor): simplify by enforcing consistent order

- api/v1alpha1/pullrequest_types.go
- config/crd/bases/promoter.argoproj.io_pullrequests.yaml
- dist/install.yaml
Probably lower value than the spec field, but still nice to be explicit.
> feat: add enum validation for PR status state

- internal/git/git.go
fixes: https://github.com/argoproj-labs/gitops-promoter/issues/280
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons
> fix: use common parent when diffing diff

- internal/controller/argocdcommitstatus_controller.go
Causes a panic if an app does not have a LastTransitionTime in its status. Assuming that if the Revision has not changed, we don't need to requeue if the LastTransitionTime is not present.
LastTransitionTime is not always set for versions before this change https://github.com/argoproj/argo-cd/pull/23018
> fix: add nil check for ArgoCD LastTransitionTime

- api/v1alpha1/common_types.go
- config/crd/bases/promoter.argoproj.io_clusterscmproviders.yaml
- config/crd/bases/promoter.argoproj.io_scmproviders.yaml
- config/samples/promoter_v1alpha1_clusterscmprovider.yaml
- config/samples/promoter_v1alpha1_scmprovider.yaml
- dist/install.yaml
- docs/example-resources/ClusterScmProvider.yaml
- docs/example-resources/ScmProvider.yaml
- internal/scms/github/git_operations.go
Setting github.domain to github.com causes it to use an incorrect API endpoint. Avoid using the invalid example in docs.
> fix: avoid invalid examples for github domain

- .goreleaser.yaml
From the most recent release build:
```
• DEPRECATED: archives.format should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
```
> chore(ci): update deprecated format field

- internal/controller/argocdcommitstatus_controller.go
- internal/controller/changetransferpolicy_controller.go
- internal/git/git.go
Clarified the design of the `GitOperations` struct and made LsRemote a static function instead of a receiver.
> chore(refactor): make LsRemote a static function instead of a receiver

- api/v1alpha1/argocdcommitstatus_types.go
- config/crd/bases/promoter.argoproj.io_argocdcommitstatuses.yaml
- dist/install.yaml
- docs/example-resources/ArgoCDCommitStatus.yaml
- internal/controller/argocdcommitstatus_controller.go
- internal/controller/promotionstrategy_controller_test.go
Closes https://github.com/argoproj-labs/gitops-promoter/issues/408
> fix(acdcs): sort status.applicationsSelected (#408)

- cmd/main.go
- go.mod
- go.sum
- internal/controller/suite_test.go
- internal/utils/scheme.go
* Fix initilization of multi-cluster kubeconfig provider
* Update tests to use a new schema instead of appending to existing
> fix: initalize multi-cluster provider and use new schema for tests to match main

- api/v1alpha1/commitstatus_types.go
- config/crd/bases/promoter.argoproj.io_commitstatuses.yaml
- dist/install.yaml
Just provides a bit of defense-in-depth agains someone trying to get a `script:` url into the UI via a CommitStatus CR.
> chore(cs): require http or https protocol on commitstatus url

- config/rbac/role.yaml
- dist/install.yaml
- internal/controller/promotionstrategy_controller.go
fixes: https://github.com/argoproj-labs/gitops-promoter/issues/424
This is also included in the leader-election-role, however that is a role not a cluster role and so only works if you install PS directly in the same namespace as the promoter.
> fix: add events rbac

- ui/components-lib/src/components/Card.tsx
- ui/components-lib/src/components/CommitInfo.tsx
- ui/shared/src/types/promotion.ts
- ui/shared/src/utils/PSData.ts
> fix(ui): hide unpopulated commit info
